project:
  type: book
  output-dir: docs 

book:
  title: "Análisis Real 1"
  author: "Estudiante: Hugo Apolinar Lira Cortés <br> Profesor: Felipe Alfaro Aguilar"
  
  # --- AQUÍ ESTÁ EL TRUCO ---
  navbar:
    logo: UACM.png
    title: "Universidad Autónoma de la Ciudad de México | ANÁLISIS REAL 1" # Nombre Institución + Materia
    background: "#1a3a5a" # Un azul marino que combine con Superhero
    search: true
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - series.qmd

    

format:
  html:
    theme: superhero   # Para que sea oscuro y elegante
    css: custom.css
    toc: true        # Índice interno a la derecha
    