project:
  type: book
  output-dir: docs 

book:
  title: "Análisis Real 1"
  author: "Estudiante: Hugo Apolinar Lira Cortés <br> Profesor: Felipe Alfaro Aguilar"
  

  
  chapters:
    - index.qmd
    - series.qmd

    
format:
  html:
    theme:
      - superhero  
      - custom.scss
    toc: true
    number-sections: true
    css: styles.css # Opcional, si quieres CSS puro aparte
    
